version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App"
    links:
      - db
    ports:
      - "8000:5000"
  
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - '6379'
  
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: "MySQL_Database"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
  worker:
    build: ./workerNew
    container_name: "workerNew"
    command: rq worker --with-scheduler -u "redis://redis:6379"
    deploy:
      replicas: 1
    depends_on:
      - redis