# FROM python:3.7-alpine
# # COPY . /app
# WORKDIR /app
# RUN pip install -r requirements.txt
# EXPOSE 5000

# COPY app.py/app
# CMD python3 app.py


# FROM python:3.7-alpine
# EXPOSE 5000
# COPY . /app
# WORKDIR /app.py

# COPY requirements.txt/app
# RUN pip install -r requirements.txt
# # RUN pip3 install -r requirements.txt
# COPY app.py/app
# CMD python app.py

# FROM python:3.7-alpine
# COPY . /app
# WORKDIR /app
# RUN pip install -r requirements.txt
# EXPOSE 5000
# CMD ["python", "app.py"]

FROM python:3.7-alpine
EXPOSE 5000
COPY ./app
WORKDIR ./app
RUN pip3 install -r requirements.txt
CMD ["python3", "app.py"]

# CMD python app.py
